### ISSUE TITLE
Nix build is stale

### ISSUE THREAD

**Issue by emilypi** [haskell-waargonaut/waargonaut#78]
Help appreciated.

**Comment by gwils** [comment]
Does waargonaut need to come with a nix build? If I were using it in my project, I would probably callCabal2Nix on it and go from there.
I'm not the nix expert though.

**Comment by emilypi** [comment]
Usually I `cabal2Nix` as a courtesy, but I'm not sold on it, because it's huge upkeep if you're not on a Nix machine. I'm in favor of nuking it if the rest of the active maintainership agrees.

**Comment by tonymorris** [comment]
+1

rule: if nix gets in the way, move it.

**Comment by gwils** [comment]
I agree, to whatever extent I could be considered "active maintainership"...
